<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<title>Music Center</title>';
echo '<link rel="stylesheet" href="Style.css">';
echo '</head>';
echo '<body>';
echo '';
echo '<div>';
echo '<h1>Music Center</h1>';
echo '<form action="form_validation.php" method="post">';
echo 'Song Title:';
echo '<input type="text" name="title" required>';
echo '<br>';
echo 'Album Name:';
echo '<input type="text" name="album" required>';
echo '<br>';
echo 'Released Date:';
echo '<input type="date" name="releaseDate" required>';
echo '<br>';
echo 'Composer Name:';
echo '<input type="text" name="composer" required>';
echo '<br>';
echo 'Genre:';
echo '<select name="genre" required>';
echo '<option value="pop">Pop</option>';
echo '<option value="rock">Rock</option>';
echo '<option value="blues">Blues</option>';
echo '<option value="hiphop">Hiphop</option>';
echo '<option value="folk">Folk</option>';
echo '</select>';
echo '<br>';
echo "Photo of the song's musicians:";
echo '<div class="chooseFile">';
echo 'Choose File';
echo '<input type="file" class="hide_file" name="photo" accept="image/*" required>';
echo '</div>';
echo '<br><br>';
echo '<input type="reset" value="Clear">';
echo '<input type="submit" value="Add">';
echo '</form>';
echo '<button onclick="window.location=\'/musiccenter/songs.php\';">Check Songs List</button>';
echo '</div>';
echo '';
echo '</body>';
echo '</html>';

?>